name: thirdPanel
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.9
    - pytest
    - sphinx
    - xarray 
    - numpy 
    - pandas
    - matplotlib
    - cartopy
    - tqdm
    - seaborn
    - eofs    
